# Generated by Django 4.2.2 on 2023-07-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Offer',
                'verbose_name_plural': 'Products Offer',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='address_name',
            field=models.CharField(default='sample', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='special_offers',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ShopPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop-pictures/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_photos', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.CharField(max_length=255)),
                ('walk_in_description', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(related_name='products_offer', to='shop.productoffer')),
            ],
            options={
                'verbose_name': 'Product Information',
                'managed': True,
            },
        ),
    ]
