# Generated by Django 4.2.2 on 2023-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='product_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products_offer', to='shop.productoffer'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='walk_in_product_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
