# Generated by Django 4.2.2 on 2023-07-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productoffer_shop_address_name_shop_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='is_available',
        ),
    ]
