# Generated by Django 4.2.2 on 2023-09-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('shop', '0002_alter_shop_product_description_alter_shop_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_offer', to='shop.productoffer'),
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_review', to='shop.shop')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shop_review', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'ShopReview',
                'verbose_name_plural': 'ShopReviews',
                'managed': True,
            },
        ),
    ]
