# Generated by Django 4.2.2 on 2023-09-01 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_products_shopreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopreview',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopreview',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
